export const productList = [
  {
    id: 504,
    title: "Classic Blue Baseball Cap",
    price: 86,
    description:
      "Top off your casual look with our Classic Blue Baseball Cap, made from high-quality materials for lasting comfort. Featuring a timeless six-panel design with a pre-curved visor, this adjustable cap offers both style and practicality for everyday wear.",
    images: [
      "https://i.imgur.com/wXuQ7bm.jpeg",
      "https://i.imgur.com/BZrIEmb.jpeg",
      "https://i.imgur.com/KcT6BE0.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 505,
    title: "Classic Red Baseball Cap",
    price: 35,
    description:
      "Elevate your casual wardrobe with this timeless red baseball cap. Crafted from durable fabric, it features a comfortable fit with an adjustable strap at the back, ensuring one size fits all. Perfect for sunny days or adding a sporty touch to your outfit.",
    images: [
      "https://i.imgur.com/cBuLvBi.jpeg",
      "https://i.imgur.com/N1GkCIR.jpeg",
      "https://i.imgur.com/kKc9A5p.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 506,
    title: "Classic Black Baseball Cap",
    price: 58,
    description:
      "Elevate your casual wear with this timeless black baseball cap. Made with high-quality, breathable fabric, it features an adjustable strap for the perfect fit. Whether you’re out for a jog or just running errands, this cap adds a touch of style to any outfit.",
    images: [
      "https://i.imgur.com/KeqG6r4.jpeg",
      "https://i.imgur.com/xGQOw3p.jpeg",
      "https://i.imgur.com/oO5OUjb.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 507,
    title: "Classic White Crew Neck T-Shirt",
    price: 39,
    description:
      "Elevate your basics with this versatile white crew neck tee. Made from a soft, breathable cotton blend, it offers both comfort and durability. Its sleek, timeless design ensures it pairs well with virtually any outfit. Ideal for layering or wearing on its own, this t-shirt is a must-have staple for every wardrobe.",
    images: [
      "https://i.imgur.com/axsyGpD.jpeg",
      "https://i.imgur.com/T8oq9X2.jpeg",
      "https://i.imgur.com/J6MinJn.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 508,
    title: "Sleek Wireless Headphone & Inked Earbud Set",
    price: 44,
    description:
      "Experience the fusion of style and sound with this sophisticated audio set featuring a pair of sleek, white wireless headphones offering crystal-clear sound quality and over-ear comfort. The set also includes a set of durable earbuds, perfect for an on-the-go lifestyle. Elevate your music enjoyment with this versatile duo, designed to cater to all your listening needs.",
    images: [
      "https://i.imgur.com/yVeIeDa.jpeg",
      "https://i.imgur.com/jByJ4ih.jpeg",
      "https://i.imgur.com/KXj6Tpb.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 2,
      name: "Electronics",
      image: "https://i.imgur.com/ZANVnHE.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 509,
    title: "Sleek White & Orange Wireless Gaming Controller",
    price: 69,
    description:
      "Elevate your gaming experience with this state-of-the-art wireless controller, featuring a crisp white base with vibrant orange accents. Designed for precision play, the ergonomic shape and responsive buttons provide maximum comfort and control for endless hours of gameplay. Compatible with multiple gaming platforms, this controller is a must-have for any serious gamer looking to enhance their setup.",
    images: [
      "https://i.imgur.com/ZANVnHE.jpeg",
      "https://i.imgur.com/Ro5z6Tn.jpeg",
      "https://i.imgur.com/woA93Li.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 2,
      name: "Electronics",
      image: "https://i.imgur.com/ZANVnHE.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 510,
    title: "Classic Black T-Shirt",
    price: 35,
    description:
      "Elevate your everyday style with our Classic Black T-Shirt. This staple piece is crafted from soft, breathable cotton for all-day comfort. Its versatile design features a classic crew neck and short sleeves, making it perfect for layering or wearing on its own. Durable and easy to care for, it's sure to become a favorite in your wardrobe.",
    images: [
      "https://i.imgur.com/9DqEOV5.jpeg",
      "https://i.imgur.com/ae0AEYn.jpeg",
      "https://i.imgur.com/mZ4rUjj.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 511,
    title: "Classic White Tee - Timeless Style and Comfort",
    price: 73,
    description:
      "Elevate your everyday wardrobe with our Classic White Tee. Crafted from premium soft cotton material, this versatile t-shirt combines comfort with durability, perfect for daily wear. Featuring a relaxed, unisex fit that flatters every body type, it's a staple piece for any casual ensemble. Easy to care for and machine washable, this white tee retains its shape and softness wash after wash. Pair it with your favorite jeans or layer it under a jacket for a smart look.",
    images: [
      "https://i.imgur.com/Y54Bt8J.jpeg",
      "https://i.imgur.com/SZPDSgy.jpeg",
      "https://i.imgur.com/sJv4Xx0.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 512,
    title: "Sleek Comfort-Fit Over-Ear Headphones",
    price: 28,
    description:
      "Experience superior sound quality with our Sleek Comfort-Fit Over-Ear Headphones, designed for prolonged use with cushioned ear cups and an adjustable, padded headband. Ideal for immersive listening, whether you're at home, in the office, or on the move. Their durable construction and timeless design provide both aesthetically pleasing looks and long-lasting performance.",
    images: [
      "https://i.imgur.com/SolkFEB.jpeg",
      "https://i.imgur.com/KIGW49u.jpeg",
      "https://i.imgur.com/mWwek7p.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 2,
      name: "Electronics",
      image: "https://i.imgur.com/ZANVnHE.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 513,
    title: "Efficient 2-Slice Toaster",
    price: 48,
    description:
      "Enhance your morning routine with our sleek 2-slice toaster, featuring adjustable browning controls and a removable crumb tray for easy cleaning. This compact and stylish appliance is perfect for any kitchen, ensuring your toast is always golden brown and delicious.",
    images: [
      "https://i.imgur.com/keVCVIa.jpeg",
      "https://i.imgur.com/afHY7v2.jpeg",
      "https://i.imgur.com/yAOihUe.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 2,
      name: "Electronics",
      image: "https://i.imgur.com/ZANVnHE.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
  {
    id: 520,
    title: "Sleek Modern Leather Sofa",
    price: 53,
    description:
      "Enhance the elegance of your living space with our Sleek Modern Leather Sofa. Designed with a minimalist aesthetic, it features clean lines and a luxurious leather finish. The robust metal legs provide stability and support, while the plush cushions ensure comfort. Perfect for contemporary homes or office waiting areas, this sofa is a statement piece that combines style with practicality.",
    images: [
      "https://i.imgur.com/Qphac99.jpeg",
      "https://i.imgur.com/dJjpEgG.jpeg",
      "https://i.imgur.com/MxJyADq.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 3,
      name: "Title changed",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T22:57:54.000Z",
    },
  },
  {
    id: 523,
    title: "Modern Elegance Teal Armchair",
    price: 25,
    description:
      "Elevate your living space with this beautifully crafted armchair, featuring a sleek wooden frame that complements its vibrant teal upholstery. Ideal for adding a pop of color and contemporary style to any room, this chair provides both superb comfort and sophisticated design. Perfect for reading, relaxing, or creating a cozy conversation nook.",
    images: [
      "https://i.imgur.com/6wkyyIN.jpeg",
      "https://i.imgur.com/Ald3Rec.jpeg",
      "https://i.imgur.com/dIqo03c.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 3,
      name: "Title changed",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T22:57:54.000Z",
    },
  },
  {
    id: 524,
    title: "Modern Minimalist Workstation Setup",
    price: 49,
    description:
      "Elevate your home office with our Modern Minimalist Workstation Setup, featuring a sleek wooden desk topped with an elegant computer, stylish adjustable wooden desk lamp, and complimentary accessories for a clean, productive workspace. This setup is perfect for professionals seeking a contemporary look that combines functionality with design.",
    images: [
      "https://i.imgur.com/3oXNBst.jpeg",
      "https://i.imgur.com/ErYYZnT.jpeg",
      "https://i.imgur.com/boBPwYW.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 3,
      name: "Title changed",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T22:57:54.000Z",
    },
  },
  {
    id: 525,
    title: "Elegant Solid Wood Dining Table",
    price: 67,
    description:
      "Enhance your dining space with this sleek, contemporary dining table, crafted from high-quality solid wood with a warm finish. Its sturdy construction and minimalist design make it a perfect addition for any home looking for a touch of elegance. Accommodates up to six guests comfortably and includes a striking fruit bowl centerpiece. The overhead lighting is not included.",
    images: [
      "https://i.imgur.com/4lTaHfF.jpeg",
      "https://i.imgur.com/JktHE1C.jpeg",
      "https://i.imgur.com/cQeXQMi.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 3,
      name: "Title changed",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T22:57:54.000Z",
    },
  },
  {
    id: 526,
    title: "Modern Ergonomic Office Chair",
    price: 71,
    description:
      "Elevate your office space with this sleek and comfortable Modern Ergonomic Office Chair. Designed to provide optimal support throughout the workday, it features an adjustable height mechanism, smooth-rolling casters for easy mobility, and a cushioned seat for extended comfort. The clean lines and minimalist white design make it a versatile addition to any contemporary workspace.",
    images: [
      "https://i.imgur.com/3dU0m72.jpeg",
      "https://i.imgur.com/zPU3EVa.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 3,
      name: "Title changed",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T22:57:54.000Z",
    },
  },
  {
    id: 527,
    title: "Futuristic Holographic Soccer Cleats",
    price: 39,
    description:
      "Step onto the field and stand out from the crowd with these eye-catching holographic soccer cleats. Designed for the modern player, these cleats feature a sleek silhouette, lightweight construction for maximum agility, and durable studs for optimal traction. The shimmering holographic finish reflects a rainbow of colors as you move, ensuring that you'll be noticed for both your skills and style. Perfect for the fashion-forward athlete who wants to make a statement.",
    images: [
      "https://i.imgur.com/qNOjJje.jpeg",
      "https://i.imgur.com/NjfCFnu.jpeg",
      "https://i.imgur.com/eYtvXS1.jpeg",
    ],
    creationAt: "2025-02-03T10:45:58.000Z",
    updatedAt: "2025-02-03T10:45:58.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2025-02-02T13:15:11.000Z",
      updatedAt: "2025-02-02T13:15:11.000Z",
    },
  },
];
